### ISSUE TITLE
Login to avoid download limit

### ISSUE THREAD

**Issue by soyuka** [BenoitZugmeyer/addic7ed-cli#17]
Hi,

Today I had this error:
```
Fatal error: Daily Download count exceeded.
```

Would it be possible to add addic7ed username/password so that the script use my account to download subs?

**Comment by JoelSjogren** [comment]
I have done some research and it is possible to login using python.

    import cookielib
    import urllib
    import urllib2

    url = 'http://www.addic7ed.com/dologin.php'
    values = {'username' : 'JoelSjogren',
              'password' : 'thisisnotmypassword' }

    data = urllib.urlencode(values)
    cookies = cookielib.CookieJar()

    opener = urllib2.build_opener(
        urllib2.HTTPRedirectHandler(),
        urllib2.HTTPHandler(debuglevel=0),
        urllib2.HTTPSHandler(debuglevel=0),
        urllib2.HTTPCookieProcessor(cookies))

    response = opener.open(url, data)
    the_page = response.read()
    http_headers = response.info()
    # The login cookies should be contained in the cookies variable

After that it was possible so visit http://www.addic7ed.com/panel.php using

    response2 = opener.open('http://www.addic7ed.com/panel.php', data)
    the_page2 = response2.read()

and I could see my username in `the_page2` so I was still logged in.

**Comment by JoelSjogren** [comment]
Something is wrong. I just downloaded subtitles for all 78 episodes of Heroes without logging in. One episode per second. How much/what did you download to cause the error?

**Comment by BenoitZugmeyer** [comment]
Thanks for your interest, I'll try to do something. @JoelSjogren , as this project uses the python module [`requests`](http://docs.python-requests.org), you don't have to deal with all that stuff to make HTTP requests supporting cookies.

**Comment by soyuka** [comment]
@JoelSjogren I just downloaded 4 subs yesterday, weird that I had this error. I'll try to reproduce again this evening and let you know.

**Comment by BenoitZugmeyer** [comment]
Ok I released the `1.0-beta0` version with login support and python3 support, please tell me if everything works for you.

**Comment by soyuka** [comment]
I'll try to get more than 15 subs but so far so good.

A small thing though, optional arguments can't be before `file` if no positional argument is provided:
```
❯ addic7ed -l fr [file]
addic7ed: error: argument command: invalid choice: 'fr' (choose from 'search', 'login', 'logout')
# With arguments at the end everything goes well
❯ addic7ed [file] -l fr
```

**Comment by BenoitZugmeyer** [comment]
Should be fixed

**Comment by soyuka** [comment]
Closing for now, I'll reopen if I stumble into this again, thx for the work!
