### ISSUE TITLE
Is is possible to...

### ISSUE THREAD

**Issue by 1boko1** [BenoitZugmeyer/addic7ed-cli#19]
Is it possible to include one option in order to automaticaly move the 'downloaded_file.srt' on the desktop (for example)?

**Comment by soyuka** [comment]
Are you talking about redirecting output?

```
addic7ed search -l french -bb -q movie > test.srt
```

This could be a nice feature.

**Comment by BenoitZugmeyer** [comment]
You can already do that : `addic7ed -q query ~/Desktop/downloaded_file.srt` or did you think of something else?

**Comment by soyuka** [comment]
Oh that's nice thanks!
