### ISSUE TITLE
can you implement a script like this?

### ISSUE THREAD

**Issue by 1boko1** [BenoitZugmeyer/addic7ed-cli#20]
Hello
First let me tell you two things:
   - English is not my primary language so please  forgive me if if my english seems bad or rude
   - Your script is the best I've found so far so thanks for your work!
   
 I download a lot of tv shows every days so it's a little boring to have to type the name of every video I download in the cli one by one. I just wanted to type a few letter and not more in the terminal.

Yes I now I'm a little lasy... and maybe didn't now where to look but I didn’t see any option in your script to do what I wanted (3 steps):
1)automatically scan a specific directory to find every videos in it 
2)download automatically every subtitle which match  with the name of  all the  video found at the step 1)
3) move the subtitle in the same dir than the video files

So I decided to make my own script (which use yours) in order to help you implement an option to improve your script or help other people who want the same things that me.
(I'm a beginner in python so there are maybe a better way to do this)

```
#!/usr/bin/python
import os, sys, os.path, shutil
import subprocess

# please adapt theses two lines:
src_dir = '/home/XXX/'         # your personnal directory XXX is your user name     
dst_dir = '/home/XXX/Videos/'  # your video directory 

def scan():
    fw = open("/tmp/tmp_addic7ed.txt", "w")	
    for file_name in os.listdir(dst_dir):
	if file_name.endswith(('.mp4', '.avi', '.mkv', '.flv')): # you can add more type of extensions
		print >>fw, file_name
    fw.close()

def move():
    for f in os.listdir(src_dir):
    	src_file = os.path.join(src_dir, f)
        dst_file = os.path.join(dst_dir, f)  
    	if f.endswith('.srt'):
        	if os.path.exists(dst_file):
                	os.remove(dst_file)
                shutil.move(src_file,dst_dir)

def main():   	
   scan()   
   f = open("/tmp/tmp_addic7ed.txt", "r")
   for line in f.read().split('\n'):
	if line:
		subprocess.call(["addic7ed", line]) 
		move()
	if not line:
        	break
   f.close()
   os.remove("/tmp/tmp_addic7ed.txt")
  

main()
```
Just put this script in /home/xxx directory

**Comment by BenoitZugmeyer** [comment]
I won't implement directory scanning in `addic7ed`, because other UNIX tools can do this much better than me. Keep in mind that `addic7ed` can take any number of file arguments, so if you are using a Linux or OSX shell, here is some examples to do what you want:

```bash
# Find subtitles for all mkv files in one directory
addic7ed -i *.mkv

# Find subtitles for all mkv files in one directory and its subdirectories
find -iname '*.mkv' | xargs addic7ed -i

# Find subtitles for all mkv, avi and mp4 files in one directory and its subdirectories
find -iname '*.mkv' -or -iname '*.avi' -or -iname '*.mp4' | xargs addic7ed -i
```

Put something like this in a bash script if you don't want to type it everytime.

Note the `-i` option everywhere, so `addic7ed` will skip the given file if the `.srt` already exists. You don't have to move the subtitles as it will be downloaded directly next to the video file.

Tell me if this works for you.

NB: here is a much simpler version of your python script:
```python
#!/usr/bin/python
import os, subprocess

dst_dir = '/home/XXX/Videos'

for file_name in os.listdir(dst_dir):
    if file_name.endswith(('.mp4', '.avi', '.mkv', '.flv')): # you can add more type of extensions
        subprocess.call(['addic7ed', os.path.join(dst_dir, file_name)])
```

**Comment by 1boko1** [comment]
Thanks a lot!
Indeed this command work fine! I didn't know it was possible.

If I want to find subtitles for all mkv, avi and mp4 files in a specific directory and its subdirectories
```
cd  && cd /home/XXX/Videos &&
find -iname '*.mkv' -or -iname '*.avi' -or -iname '*.mp4' | xargs addic7ed -i
```
And if  I want to find subtitles in a specific folder only (not recursive)
```
cd  && cd /home/XXX/Videos &&
find -maxdepth 1 -type f -iname '*.mkv' -or -iname '*.avi' -or -iname '*.mp4' | xargs addic7ed -i
```
With the use of an alias it's perfect!

You should perhaps put theses commands in your README file or in comment in your code in case it can help  someone else 
NB: Thanks you for the python script help too.
