### ISSUE TITLE
Season Subtitles Request

### ISSUE THREAD

**Issue by knox2** [BenoitZugmeyer/addic7ed-cli#23]
is there a way you can use their "multi-download option" which let's you download complete season subs at once in a zip file thereby avoiding to hit the limits per day for downloading each episode's subtitiles

**Comment by soyuka** [comment]
```
for f in ./*.mkv; do addic7ed search -bb -l fr $f; done; mkdir subs; mv *.srt subs/; zip -r subs.zip subs
```

**Comment by knox2** [comment]
I already use login...as a registered user I am limited to 40 per 24 hrs.. will the above code work as 1 call or the number of episodes in the season....eg 24 Season 1 has 24 episodes.. using multi download on the web i can select them all and download as a single call...ie 39 will remail
will this do the same or will it count as 24 calls i,e 16 will remail

**Comment by BenoitZugmeyer** [comment]
This is an interesting idea. I will work on this whenever I can!

**Comment by soyuka** [comment]
Indeed @knox2 it'll do 24 calls, sorry about my misunderstood :).

**Comment by knox2** [comment]
@soyuka that seems to be the call plus :
-language and 
-hearing filters

**Comment by BenoitZugmeyer** [comment]
@knox2 I just commited what you asked for, could you test if it's ok for you? To use it, you will need to be logged in (with the `addic7ed login` command) and provide multiple videos at the same time. It will inform the user by displaying "Using multi-download".

**Comment by knox2** [comment]
Sorry for taking long to reply.... @BenoitZugmeyer , does it download a zip or one by one, because mine downloads one by one..

**Comment by BenoitZugmeyer** [comment]
@knox2 if it says "Using multi-download", it downloads a zip with all the subtitles, then extracts subtitles to the correct places. If it doesn't say this, please make sure that:
* you are using the latest version of addic7ed-cli (please check the [Latest](https://github.com/BenoitZugmeyer/addic7ed-cli#latest) section in the readme)
* you are authentified (use the `addic7ed login` command)
* you provided multiple files to the command line

**Comment by knox2** [comment]
It does say "Using multi-download", It extracts them correctly..Thanks @BenoitZugmeyer, I believe this issue is closed now

**Comment by BenoitZugmeyer** [comment]
Yay! I'll release this soon.
