### ISSUE TITLE
Ability to skip

### ISSUE THREAD

**Issue by vBm** [BenoitZugmeyer/addic7ed-cli#24]
This ticket is about two things tho.

Currently there's no way to skip downloads except to terminate script.
By design default value is always `[1]`, would be nice if we could type `N(o)` or `S(kip)` or whatever you decide to skip current file in the queue.

2nd part of the ticket is regarding skipping already downloaded files. Would be nice if we could have option for config that would auto skip already existing subs.

**Comment by BenoitZugmeyer** [comment]
Here you go! please test it and tell me if it looks fine.

**Comment by BenoitZugmeyer** [comment]
Oh, in case it's not clear: you can now add the "ignore" flag in the configuration file (~/.config/addic7ed) like this:

```
[flags]
ignore
```

I thought it worked but apparently not.

**Comment by vBm** [comment]
Works. Thanks.

About conf file, i was never been able to make it work under Windows ;x (%APPDATA%/config as per README but still doesn't get picked up here)

**Comment by BenoitZugmeyer** [comment]
Ok, I'll try to make it work soon.
