### ISSUE TITLE
Is it possible to add language tags to filename

### ISSUE THREAD

**Issue by hansdg1** [BenoitZugmeyer/addic7ed-cli#26]
In order for Plex to know the language of the subtitle, you need to have the ISO 639 as part of the filename. Could support for that be added to this already amazing tool?

Ex:
Instead of 
`Person of Interest - S04E22 - YHWH.srt`
add the language tag before srt 
`Person of Interest - S04E22 - YHWH.eng.srt`

**Comment by BenoitZugmeyer** [comment]
Sure! here you go.
