### ISSUE TITLE
Is it possible to...

### ISSUE THREAD

**Issue by 1boko1** [BenoitZugmeyer/addic7ed-cli#27]
First, thanks  a lot for your script.

Just a minor drawback, though:
When I use the command: `addic7ed -i -bb supernatural.1111.hdtv-lol[ettv].mp4`
I got :
```
------------------------------
Target SRT file: supernatural.1111.hdtv-lol[ettv].srt
Supernatural - 01x01 - Pilot
English - DVDRip.SAiNTS  Completed 
```
I have to change the name and write : `addic7ed -i -bb supernatural.S11E11.hdtv-lol[ettv].mp4`**
to obtain the good file:
```
------------------------------
Target SRT file: supernatural.S11E11.hdtv-lol[ettv].srt
Supernatural - 11x11 - Into the Mystic
English - DIMENSION  Completed 
```

At first, i thought the script could not understand: 1111 = S11E11
Yet, when I write `addic7ed -i -bb supernatural.111.hdtv-lol[ettv].mp4`
the script manage to understand 111 = S1E11
```
------------------------------
Target SRT file: supernatural.111.hdtv-lol[ettv].srt
Supernatural - 01x11 - Scarecrow
English - DVDRip.SAiNTS  Completed
```
Is it possible to correct this?
Thanks

**Comment by BenoitZugmeyer** [comment]
Here you go!

**Comment by 1boko1** [comment]
Thanks !
