### ISSUE TITLE
Is it possible to...

### ISSUE THREAD

**Issue by hansdg1** [BenoitZugmeyer/addic7ed-cli#31]
Add a switch/config file option to add "forced" into the path of the output filename. Plex can interpret these and appropriately tag them as "forced" subtitle tracks. 

Ex: Madam.Secretary.S03E05.The.French.Revolution.1080p.x264.DTS.eng.forced.srt

**Comment by BenoitZugmeyer** [comment]
This seems to be a very specific use case. I could add an option, but before that let me suggest you two ways of doing this.
* You can already output srt file with a given name. This is a bit manually though. Ex:
```
addic7ed -l english --no-lang-suffix Madam.Secretary.S03E05.The.French.Revolution.1080p.x264.DTS.eng.forced.srt
````
* You can automate this by using the command `rename` (commonly distributed in linux distros inside the util-linux package)
```
addic7ed -l english --lang-suffix Madam.Secretary.S03E05.The.French.Revolution.1080p.x264.DTS.mkv && rename -v .eng.srt .eng.forced.srt *.srt 
```
Would one of those suggestions work for you?

**Comment by BenoitZugmeyer** [comment]
Closing this, feel free to add a comment if you think both solutions don't work for you.
