### ISSUE TITLE
No lang in the srt filename

### ISSUE THREAD

**Issue by IKIKN** [BenoitZugmeyer/addic7ed-cli#34]
Hi,

First of all, thanks for this great script ! 

Is there a way to automatically add the language in the srt filename ? For example, when I run this command :

addic7ed -l french The\ Strain\ -\ S04E06\ -\ Tainted\ Love.mkv

I get a file named : The Strain - S04E06 - Tainted Love.srt

I would like to have "fr" included in the file name, before the srt, like this :

The Strain - S04E06 - Tainted Love.fr.srt

I found a workaround, which is to type :

addic7ed -l french The\ Strain\ -\ S04E06\ -\ Tainted\ Love.fr.mkv

But it's kind of ugly to have to do that.

(Please note that I'm using the last version of the script, not the stable one, but I tried both).

Thanks !

**Comment by BenoitZugmeyer** [comment]
Yes, you can use the option `--lang-suffix` (see `addic7ed search --help`).

You can also put it in your `~/.config/addic7ed` file so it'll be on by default, something like this:
```
[flags]
lang-suffix
```

Cheers!

**Comment by IKIKN** [comment]
Thanks for the answer. I tried what you said and it actually renames the file with "fra", like this :

The Strain - S04E06 - Tainted Love.fra.srt

And Plex doesn't seem to recognize that "fra" is "fr". Is this normal ? Shouldn't it be "fr" and not "fra" ? 

Thanks

**Comment by BenoitZugmeyer** [comment]
The original issue was already for supporting Plex: https://github.com/BenoitZugmeyer/addic7ed-cli/issues/26

The author asked me to support ISO-639-2 language codes (3 characters), so I did, based on [this list](http://www-01.sil.org/iso639-3/codes.asp?order=639_2&letter=f). BTW, according to the [Plex documentation](https://support.plex.tv/hc/en-us/articles/200471133-Adding-Local-Subtitles-to-Your-Media), it should work. Does it works with `fr` and `fre`?

**Comment by IKIKN** [comment]
Yes, it does work with "fr" and with "fre".

**Comment by BenoitZugmeyer** [comment]
Thanks, I'll change `fre` to `fra` later on.

**Comment by IKIKN** [comment]
Thanks a lot !

**Comment by BenoitZugmeyer** [comment]
It's published!

**Comment by IKIKN** [comment]
It's "fre" instead of "fra" now, thanks a lot !
