### ISSUE TITLE
Generated search query fails (Status 304) - Site may have changed format of the query URL

### ISSUE THREAD

**Issue by timothymowens** [BenoitZugmeyer/addic7ed-cli#36]
addic7ed-cli generates URLs like this:

- http://www.addic7ed.com/search.php?search=show+title+5x10&submit=Search

I believe the site now expects the URL to be like this:

- http://www.addic7ed.com/srch.php?search=show+title+5x10&Submit=Search

Subtitle searches with addic7ed-cli are failing for me (status 304) until this URL issue is resolved.

Notice the 'srch.php' and 'Submit' in the new URL vs 'search.php' and 'submit' in the current addic7ed-cli generated URL (not sure if the casing of Submit is important here, just noticed that it was different).

Details of my system:

- Ubuntu 16.04.04 x64
- python v2.7
- addic7ed-cli v1.42

**Comment by pannal** [comment]
The original URL still works.

304 is addic7ed's way of telling you that you're making too many requests with your current IP or useragent.

**Comment by timothymowens** [comment]
Odd.  I tried it from 3 different IPs, in browsers, using wget and using addic7ed-cli and I get 304 no matter what.

**Comment by pannal** [comment]
Hmm, a second ago your first URL of your original post worked for me in the browser. The second attempt doesn't.

**Comment by pannal** [comment]
Fun. Now it worked again - but the old endpoint doesn't return results for `search=show+title+5x10&submit=Search`: `Sorry, your search: show title 5x10 returned zero results`

The new one does.

I'm guessing they're ditching the old endpoint in an effort to reduce server load caused by libraries like this, subliminal and Sub-Zero. The 304 response usually is "stop that, too many requests".

**Comment by BenoitZugmeyer** [comment]
I'll change the endpoint in a few hours. Thanks for the heads up.

**Comment by timothymowens** [comment]
I was able to get one subtitle downloaded with addic7ed-cli, but the next one failed with a 304 the first time, then a "Sorry, your search returned zero results", even though the sub exists and is available on the site.  Something changed recently as addic7ed-cli worked great just a couple days ago.

Side note: I am using my addic7ed.com account login and checked the site to verify that I have not hit my daily download limit.

**Comment by BenoitZugmeyer** [comment]
A new version is published. Let me know if you have any other issue.
