### ISSUE TITLE
No Result - Nothing to Download

### ISSUE THREAD

**Issue by timothymowens** [BenoitZugmeyer/addic7ed-cli#39]
For the past week, addic7ed-cli says there is "No Result" and "Nothing to Download" for everything I've tried to get subtitles for.  My video files are all named correctly and the website shows the subs available.

Here's an example:

```
 # addic7ed gotham.s04e21.720p.web.x264-tbs.mkv
Target SRT file: gotham.s04e21.720p.web.x264-tbs.srt
No result

Nothing to download

```

As you can see from this link, there are subs available: http://www.addic7ed.com/serie/Gotham/4/21/A_Dark_Knight%3A_One_Bad_Day

**Comment by tim-durrant** [comment]
Yes, I concur.
However if you read their news post on the website, they’ve been having
(and still having) all sorts of search problems on their server.

I’m not convinced that altering addic7ed-cli will be of benefit until their
server is back to normal and some level of search consistency.

Just my two cents worth :-)

**Comment by soyuka** [comment]
Just update, it has been fixed https://github.com/BenoitZugmeyer/addic7ed-cli/pull/38

**Comment by timothymowens** [comment]
Thanks soyuka, I just updated a week ago, but after reading your comment, I updated once more and it is indeed working again.  Thanks!
